# Generated by Django 4.2.4 on 2023-11-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=65)),
                ('c_password', models.CharField(max_length=65)),
            ],
        ),
    ]
